import 'package:flutter/material.dart';
import '../../classroom/models/class_model.dart';
import '../../classroom/services/class_service.dart';
import '../../auth/services/auth_service.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/services/localization_service.dart';

/// Dialog for creating a new classroom
class ClassroomFormDialog extends StatefulWidget {
  const ClassroomFormDialog({super.key});

  @override
  State<ClassroomFormDialog> createState() => _ClassroomFormDialogState();
}

class _ClassroomFormDialogState extends State<ClassroomFormDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _schoolNameController = TextEditingController();
  int _selectedGrade = 1;
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _schoolNameController.dispose();
    super.dispose();
  }

  /// Validate and create classroom
  Future<void> _createClassroom() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    final user = AuthService.instance.currentUser;
    if (user == null) {
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final classroom = ClassModel(
        id: '', // Will be generated by Firestore
        name: _nameController.text.trim(),
        teacherId: user.uid,
        grade: _selectedGrade,
        schoolName: _schoolNameController.text.trim(),
        studentIds: [],
        createdAt: DateTime.now(),
      );

      await ClassService.instance.createClass(classroom);

      if (mounted) {
        Navigator.of(context).pop(true); // Return true on success
      }
    } catch (e) {
      if (mounted) {
        final isRTL = LocalizationService.instance.isRTL;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              isRTL ? 'שגיאה ביצירת כיתה: $e' : 'Error creating classroom: $e',
            ),
            backgroundColor: AppColors.error,
          ),
        );
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isRTL = LocalizationService.instance.isRTL;

    return AlertDialog(
      title: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(AppTheme.spacingSmall),
            decoration: BoxDecoration(
              color: AppColors.primary.withOpacity(0.1),
              borderRadius: BorderRadius.circular(AppTheme.radiusSmall),
            ),
            child: const Icon(
              Icons.add_circle_outline,
              color: AppColors.primary,
              size: 24,
            ),
          ),
          const SizedBox(width: AppTheme.spacingMedium),
          Text(
            isRTL ? 'יצירת כיתה חדשה' : 'Create New Classroom',
            style: const TextStyle(
              fontSize: AppTheme.fontSizeLarge,
              fontWeight: FontWeight.bold,
              color: AppColors.textPrimary,
            ),
          ),
        ],
      ),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Classroom name field
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(
                  labelText: isRTL ? 'שם הכיתה *' : 'Classroom Name *',
                  hintText: isRTL ? 'לדוגמה: כיתה א1' : 'e.g., Class 1A',
                  prefixIcon: const Icon(Icons.class_outlined),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return isRTL ? 'נא למלא שם כיתה' : 'Please enter classroom name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: AppTheme.spacingMedium),

              // Grade dropdown
              DropdownButtonFormField<int>(
                value: _selectedGrade,
                decoration: InputDecoration(
                  labelText: isRTL ? 'כיתה *' : 'Grade *',
                  prefixIcon: const Icon(Icons.school_outlined),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
                  ),
                ),
                items: List.generate(6, (index) {
                  final grade = index + 1;
                  return DropdownMenuItem(
                    value: grade,
                    child: Text(
                      isRTL ? 'כיתה $grade' : 'Grade $grade',
                      style: const TextStyle(
                        fontSize: AppTheme.fontSizeMedium,
                      ),
                    ),
                  );
                }),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedGrade = value;
                    });
                  }
                },
              ),
              const SizedBox(height: AppTheme.spacingMedium),

              // School name field
              TextFormField(
                controller: _schoolNameController,
                decoration: InputDecoration(
                  labelText: isRTL ? 'שם בית הספר *' : 'School Name *',
                  hintText:
                      isRTL ? 'לדוגמה: ביה"ס היסודי' : 'e.g., Elementary School',
                  prefixIcon: const Icon(Icons.location_city_outlined),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppTheme.radiusMedium),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return isRTL
                        ? 'נא למלא שם בית ספר'
                        : 'Please enter school name';
                  }
                  return null;
                },
              ),
            ],
          ),
        ),
      ),
      actions: [
        // Cancel button
        TextButton(
          onPressed: _isLoading ? null : () => Navigator.of(context).pop(false),
          child: Text(
            isRTL ? 'ביטול' : 'Cancel',
            style: const TextStyle(
              color: AppColors.textSecondary,
              fontSize: AppTheme.fontSizeMedium,
            ),
          ),
        ),

        // Create button
        ElevatedButton(
          onPressed: _isLoading ? null : _createClassroom,
          style: ElevatedButton.styleFrom(
            padding: const EdgeInsets.symmetric(
              horizontal: AppTheme.spacingLarge,
              vertical: AppTheme.spacingSmall,
            ),
          ),
          child: _isLoading
              ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    color: AppColors.textOnPrimary,
                  ),
                )
              : Text(
                  isRTL ? 'צור כיתה' : 'Create',
                  style: const TextStyle(
                    fontSize: AppTheme.fontSizeMedium,
                    fontWeight: FontWeight.w600,
                  ),
                ),
        ),
      ],
    );
  }
}

/// Show classroom form dialog
Future<bool?> showClassroomFormDialog(BuildContext context) {
  return showDialog<bool>(
    context: context,
    builder: (context) => const ClassroomFormDialog(),
  );
}
