// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhcOtrYocky_79LEj3lUm6rieGdV9PdM',
    appId: '1:674604133315:web:2c9b315ac005c2fb562b76',
    messagingSenderId: '674604133315',
    projectId: 'attenglish-dev',
    authDomain: 'attenglish-dev.firebaseapp.com',
    storageBucket: 'attenglish-dev.firebasestorage.app',
    measurementId: 'G-3G79L8VM57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMm60dcXr-IlL-6URiFe2K2wp45A3u8w',
    appId: '1:674604133315:android:40eab01df554e3e3562b76',
    messagingSenderId: '674604133315',
    projectId: 'attenglish-dev',
    storageBucket: 'attenglish-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9phcXCqnSOuZDUuR3G2sXKTTwHj1PQCM',
    appId: '1:674604133315:ios:4793d0336ef46ea2562b76',
    messagingSenderId: '674604133315',
    projectId: 'attenglish-dev',
    storageBucket: 'attenglish-dev.firebasestorage.app',
    iosBundleId: 'com.example.attenglish',
  );

}